apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
  - port: 31005
    nodePort: 31001
    targetPort: node-port
    protocol: TCP
  selector:
    app: helloworld
  type: NodePort
